### ISSUE TITLE
License matters

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/tokyo#1]
I think license doc should be added to this repository.

I recommend Apache 2.0.

[How to add license](https://help.github.com/articles/adding-a-license-to-a-repository/)

[Example License, Plasma MVP](https://github.com/omisego/plasma-mvp/blob/a963ce25ce29cfc33dd9a4850ef9b0aa6c6e5be4/LICENSE)

**Comment by 4000D** [comment]
Thanks for useful links. Apache 2.0 added.
