### ISSUE TITLE
priority between purchase_limit in <stages> and <valid_purchase>

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/tokyo#19]
In terms of min/max purchase_limit, 

which one is prioritized between in stages and valid_purchase?

**Comment by 4000D** [comment]
It is based on the sequence of inheritance.

**Comment by 4000D** [comment]
https://github.com/Onther-Tech/tokyo/blob/64af30deec8a1cbc632d3d26e7d724899a0d6de5/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/AuditFullFeaturesCrowdsale.sol#L12

**Comment by 4000D** [comment]
tokyo has similar inheriting model with [openzeppelin-solidity](https://github.com/OpenZeppelin/zeppelin-solidity/pull/744)
