### ISSUE TITLE
Suggestions in BaseCrowdsale.sol

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/tokyo#2]
I am auditing this: 
https://github.com/Onther-Tech/tokyo/blob/f7007f39d1868910f0f262163416b4492be9d98b/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/BaseCrowdsale.sol

I just wonder how you(@4000D) think about these suggestions.

**variable name**:
- `cap` -> `softCap` or `hardCap` like data field in input json.
https://github.com/Onther-Tech/tokyo/blob/f7007f39d1868910f0f262163416b4492be9d98b/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/BaseCrowdsale.sol#L31

**unused parameter**:
- _beneficiary field not used
https://github.com/Onther-Tech/tokyo/blob/f7007f39d1868910f0f262163416b4492be9d98b/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/BaseCrowdsale.sol#L150

**logic**:
- I would like to divide `buyTokens` into functions `buyTokens` and `buyTokensAndGenerateToBeneficiary`. `buyTokens`'s beneficiary is msg.sender, `buyTokensAndGenerateToBeneficiary`'s beneficiary is address parameter(`beneficiary`).
https://github.com/Onther-Tech/tokyo/blob/f7007f39d1868910f0f262163416b4492be9d98b/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/BaseCrowdsale.sol#L56
- To make an investment explicit, do not put logic in the fallback function, just revert it.
https://github.com/Onther-Tech/tokyo/blob/f7007f39d1868910f0f262163416b4492be9d98b/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/BaseCrowdsale.sol#L52
- In my opinion, would not it be better to separate unimplemented functions into different contracts or interfaces?
https://github.com/Onther-Tech/tokyo/blob/f7007f39d1868910f0f262163416b4492be9d98b/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/BaseCrowdsale.sol#L166

**Comment by 4000D** [comment]
`cap` is hard cap of crowdsale. 
`goal` is soft cap.
