### ISSUE TITLE
`storage` keyword usage

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/tokyo#4]
I want to know about why using the `storage` keyword.
https://github.com/Onther-Tech/tokyo/blob/3c6f03243d5c8c4d28c730c40aaa365b42e793c0/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/StagedCrowdsale.sol#L126

I know that using `memory` keyword is cheaper than using `storage` keyword and that complex type local variables are stored in `storage` by default.

but, I think using `memory` keyword does not seem to be a problem. I did not have any problems when I tested it.

test code:
```javascript
pragma solidity ^0.4.18;

contract Test {
    
  Period[] public periods;
    
  struct Period {
  uint128 balance;
  }
  
  function set(uint128 _balance) 
  public 
  {
      periods.push(Period({balance: _balance}));
  }
  
  function get() 
  internal 
  view 
  returns (uint256) 
  {
    Period memory p = periods[0];
    uint128 balance = p.balance;
    return balance;
    }
}
```

**Comment by ggs134** [comment]
I think so too.
