### ISSUE TITLE
KYC testing fails

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/tokyo#6]
Something that needs to be changed in order for the `KYC` contract test to be successful.
1. `.deployed()` -> `new()`
https://github.com/Onther-Tech/tokyo/blob/26238729d0c662828b537ebce82f9c40c6ab2819/packages/tokyo-reusable-crowdsale/test/KYC.js#L28
2. export default `'revert'` -> export default `'invalid opcode'`
https://github.com/Onther-Tech/tokyo/blob/26238729d0c662828b537ebce82f9c40c6ab2819/packages/tokyo-reusable-crowdsale/test/helpers/EVMThrow.js#L1

**Comment by 4000D** [comment]
1. yes. `tokyo-reusable-crowdsale` must have only building contracts, not the tokyo-generated contracts.

2. "revert" and "invalid opcode" should be distinguished. zeppelin's [revert](https://github.com/OpenZeppelin/zeppelin-solidity/blob/0926729c8f19f6ed147c46f5c893a012be815a5a/test/helpers/EVMRevert.js), [throw](https://github.com/OpenZeppelin/zeppelin-solidity/blob/0926729c8f19f6ed147c46f5c893a012be815a5a/test/helpers/EVMThrow.js)
