### ISSUE TITLE
Validation issue in type casting

### ISSUE THREAD

**Issue by jenny9405** [Onther-Tech/tokyo#8]
1. uint is equal to uint256, So it seems to type cast to uint8.
I think not only check for more than 0, but also need to check the validity of uint8 when it exceeds the expression range. What do you think?
https://github.com/Onther-Tech/tokyo/blob/4c8ad10f59b1612e1c4dc1900e58460161e88f92/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/StagedCrowdsale.sol#L29

2. It is not a big problem, but it seems to have the same meaning as stage and period in StagedCrowdsale Contract. Is it better to maintain consistency with the same word?
https://github.com/Onther-Tech/tokyo/blob/4c8ad10f59b1612e1c4dc1900e58460161e88f92/packages/tokyo-reusable-crowdsale/audit/full-features/contracts/base/crowdsale/StagedCrowdsale.sol#L15

**Comment by 4000D** [comment]
agree with both.

**Comment by ggs134** [comment]
Both Links do not connected to sol file.

**Comment by jenny9405** [comment]
thank you , I edited a Links.

**Comment by 4000D** [comment]
please make PR
