### ISSUE TITLE
From `accept buying tokens over stage max purchase` testing

### ISSUE THREAD

**Issue by thomashin** [Onther-Tech/tokyo#9]
I have two questions.

1. The `rate` value is 260. I think `tokenAmount ` is should be divided by `.div(coeff)`, not just multiplication(260).
https://github.com/Onther-Tech/tokyo/blob/4c8ad10f59b1612e1c4dc1900e58460161e88f92/packages/tokyo-reusable-crowdsale/audit/full-features/test/FullFeatures.js#L184
2. I wonder how `investAmount`(*wei*) can be used beyond stage's `max_purchase_limit` value.
https://github.com/Onther-Tech/tokyo/blob/4c8ad10f59b1612e1c4dc1900e58460161e88f92/packages/tokyo-reusable-crowdsale/audit/full-features/test/FullFeatures.js#L189

**Comment by thomashin** [comment]
If the `base_rate` is 200, the `coeff` value is 1000, and `is_static` is `true`, can I purchase 20 token at a price of 1 wei?

**Comment by 4000D** [comment]
1 ether = 200 token = 200e18 unit token
1 wei = 200 unit token

token price = 1 ether / 200 token = 0.005
